
#ifndef ARDUINOPROJECTMODULE_DEBUG_TILT_TOWER_CONFIG_H
#define ARDUINOPROJECTMODULE_DEBUG_TILT_TOWER_CONFIG_H

#define TILT_MOT1_B1_IN       ((uint16_t)0x0001)
#define TILT_MOT1_A1_IN       ((uint16_t)0x0002)
#define TILT_MOT1_B2_IN       ((uint16_t)0x0004)
#define TILT_MOT1_A2_IN       ((uint16_t)0x0008)
#define TILT_MOT1_EN          ((uint16_t)0x0010)
#define TILT_LED_RED          ((uint16_t)0x0020)
#define TILT_LED_GREEN        ((uint16_t)0x0040)
#define TILT_LED_BLUE         ((uint16_t)0x0080)
#define TILT_BTN_HIGH_LIMIT   ((uint16_t)0x0100)
#define TILT_BTN_LOW_LIMIT    ((uint16_t)0x0200)
#define TILT_FEED_MOTOR_IN    ((uint16_t)0x0400)
#define TILT_FEED_VALVE_IN    ((uint16_t)0x0800)

#define TILT_INVERT_OUT       ((uint16_t)(TILT_LED_RED | TILT_LED_GREEN | TILT_LED_BLUE))  

#define TILT_CONFIGURATION    ((uint16_t)~(TILT_MOT1_B1_IN | TILT_MOT1_A1_IN | TILT_MOT1_B2_IN | TILT_MOT1_A2_IN | TILT_MOT1_EN | TILT_LED_RED | TILT_LED_GREEN | TILT_LED_BLUE))

#define TILT_INPUT_MASK       (TILT_BTN_HIGH_LIMIT | TILT_BTN_LOW_LIMIT | TILT_FEED_MOTOR_IN | TILT_FEED_VALVE_IN)

#define TILT_LED_COLOR_BLACK        (0)
#define TILT_LED_COLOR_WHITE        (TILT_LED_RED | TILT_LED_GREEN | TILT_LED_BLUE)
#define TILT_LED_COLOR_RED          (TILT_LED_RED)
#define TILT_LED_COLOR_YELLOW       (TILT_LED_RED | TILT_LED_GREEN)
#define TILT_LED_COLOR_GREEN        (TILT_LED_GREEN)
#define TILT_LED_COLOR_CYAN         (TILT_LED_GREEN | TILT_LED_BLUE)
#define TILT_LED_COLOR_BLUE         (TILT_LED_BLUE)
#define TILT_LED_COLOR_MEGENTA      (TILT_LED_RED | TILT_LED_BLUE)

#endif //ARDUINOPROJECTMODULE_DEBUG_TILT_TOWER_CONFIG_H
